### ISSUE TITLE
Elements missing after parsing 

### ISSUE THREAD

**Issue by BenGraWarBuf** [manusimidt/py-xbrl#126]
for example in the following instance file:
https://www.sec.gov/Archives/edgar/data/101199/000010119921000053/ufcs-20210331_htm.xml
the element:
<ufcs:AccruedExpensesAndOtherLiabilities contextRef="i078c96718789432b87b0dd0047972763_I20210331" decimals="-3" id="id3VybDovL2RvY3MudjEvZG9jOjRkYjFiMDhlMDY0MjQ4ZWFhMjg2YmExNGNjNmNlNDIyL3NlYzo0ZGIxYjA4ZTA2NDI0OGVhYTI4NmJhMTRjYzZjZTQyMl8xOS9mcmFnOjcxMmIyMDRhNDNjNzRhOGVhMjFkYmI4ZGRhOTgwYzFmL3RhYmxlOmNiNGMyODA5YTU3YjQ5YzRhODNiMzkyYWU2MTZiMjU0L3RhYmxlcmFuZ2U6Y2I0YzI4MDlhNTdiNDljNGE4M2IzOTJhZTYxNmIyNTRfMzEtMS0xLTEtMA_ff86ac9b-8da8-4873-b7eb-5f603fa37a3c" unitRef="usd">92401000</ufcs:AccruedExpensesAndOtherLiabilities>
is missing after parsing 
this is the index page for reference:
https://www.sec.gov/Archives/edgar/data/101199/000010119921000053/0000101199-21-000053-index.htm

is not clear to me why the namespace ufcs is not being picked up.
any idea why this could be?

**Comment by manusimidt** [comment]
This is a funny one! Thanks for posting! I really wonder why this has not been discovered before 😄

Background: When parsing facts in XBRL I loop over all XML elements. In order to exclude XBRL contexts, units and schema references I have the following if condition there:
![image](https://github.com/manusimidt/py-xbrl/assets/29599104/95e3b519-5641-4923-86af-7c7bc22a73a4)


Since the company filing the document is called "**unit**edfiregroup" it has the phrase "unit" in the full XML tag and thus `py-xbrl` skips all facts filed by this company because it thinks that these facts are units and not facts.

**Comment by manusimidt** [comment]
@BenGraWarBuf should be fixed in [V 2.2.11](https://pypi.org/project/py-xbrl/2.2.11/) :)

**Comment by BenGraWarBuf** [comment]
Wow! your are a Rockstar my friend that was lightning fast.
