### ISSUE TITLE
Difference between pypi and github releases?

### ISSUE THREAD

**Issue by Cave-Johnson** [manusimidt/py-xbrl#128]
Just noticed that on github the release version is 2 minor versions behind pypi (2.2.9 github vs 2.2.11 pypi)

what the reason for the discrepancy here? Is there a changelog anywhere for the version on pypi?

**Comment by manusimidt** [comment]
Hey @Cave-Johnson 
yes, sometimes I just forget to also upload to GitHub :D 
I suspect that most users download py-xbrl over PyPI instead of manually downloading the wheels.

Currently, I don't maintain a separate changelog (changelog.txt). When I publish a new version on GitHub I try to summarize the changes and additionally, I try to describe the changes as good as possible in the commit message.

But thanks for the Reminder. Please find the lastest version [here](https://github.com/manusimidt/py-xbrl/releases/tag/v2.2.11).

**Comment by Cave-Johnson** [comment]
Thanks @manusimidt! I do tend to pull from pypi but like to look at the changelog first and i don't think there is one on pypi (i could be wrong!)

My background is security so when I see a new pypi version but not on git it sets off alarm bells that the pypi account could have been taken over and a malicious version published.
