### ISSUE TITLE
Is there a way to show the complete tags?

### ISSUE THREAD

**Issue by hakube** [manusimidt/py-xbrl#37]
Awesome library. I have a question btw if you don't mind?

Is there a way to show the complete tags for each facts?

ex.

* us-gaap:AssetsCurrent
* dei:SomeTagIntheDocument
* ticker:SomeTagInTheDocument

I'm looking to separate the standard and non-standar tag in the SEC filings

**Comment by manusimidt** [comment]
Thanks a lot! 
The tag name of each fact is discarded because it is only needed for connecting the fact with the concept from the taxonomy. The filer could theoretically also use a completely different namespace for us-gaap and then the xml-tag would change i.e: `us-gaap-2020:AssetsCurrent` instead of `us-gaap:AssetsCurrent`.

Moreover, the xml tags are only present in XBRL filings and not in the newer iXBRL filings.
For example: 
Here is a fact in **XBRL**:
```xml
 <us-gaap:Assets contextRef="FI2018Q4" unitRef="usd" decimals="-6">365725000000</us-gaap:Assets> 
``` 
And here is the same fact in **iXBRL**
```html
<ix:nonFraction contextRef="FI2018Q4" unitRef="usd" decimals="-6" format="ixt:numdotdecimal" name="us-gaap:Assets" scale="6">365,725</ix:nonFraction>
```

I would recommmend to seperate standard and non-stantard facts by looking either at the "xml_id" of the concept or by looking at the "schema_url" of the taxonomy in which the concept is defined.

![image](https://user-images.githubusercontent.com/29599104/122033465-d5df3980-cdd0-11eb-9dc6-bebea8b4cfa4.png)
